version: '3'

services:
  web:
    build: .
    container_name: app-payment
    volumes:
      - .:/home/app/payment
    ports:
      - 3000:3000
    depends_on:
      - redis

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok-payment
    env_file:
      - .env
    environment:
        NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
    command: 'http web:3000'        
    ports:
        - '4040:4040'
    depends_on:
      - web

  redis:
    image: redis:alpine3.17
    container_name: redis-payment
    ports:
      - '6379:6379'